services:
  - type: web
    name: neuroscan-ng
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt gunicorn
    startCommand: gunicorn -b 0.0.0.0:$PORT -w 1 --timeout 120 app:app
    envVars:
      - key: NEUROSCAN_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.9
